export const GET_CITY = 'GET_CITY';
export const SET_RESTAURANT_CATEGORY_IDS = 'SET_RESTAURANT_CATEGORY_IDS';
export const SET_CLASSIFY_BC = 'SET_CLASSIFY_BC';
export const SET_SEARCH_ADDRESS_NAME = 'SET_SEARCH_ADDRESS_NAME';


